###
POST http://192.168.79.130:8080/company/getPersonalInfoByIdentifier
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBUElfS0VZIjoiOTk0N2E2OTM0NmQ4MDE4ZjhhNzYyYmIzZTE1Y2M1MDMxMzgxZDY0NjcwNGYwNDNkZGNiZmYxYTQ4ZmE0ZjI1NyIsIkFQSV9TRUNSRVQiOiJVMkZzZEdWa1gxOVptSnRXYjZ2S3orM0s0YUVxdS9rYkx3ZmdLeHJJVGE0MmxLUHhDcHV1b044SFFZK28waks5bFA1aVhGS0ZpRGFUcStnam5KRlJSY1pYK2tzZkI4eTlQUlF1Y1NnQ2c3cG9PaGhVT0tVYzFtZTJpUVpiZHpzT1BUVUltL2xBODJBQ2xVMUdMcTM0ZjVPdWlXcEdIUzVudnFpRkVzbWJiY0RTUENiOFlPK0MzRjhIWXpkVHJIdDUiLCJpYXQiOjE1Nzg2NDM0MzMsImV4cCI6MTU3ODY0MzYxM30.mfJeEQJTSd9SHtOvBWxkGQd6e8xGbdeTrW8McQU3Aao

{
    "identifier": "identifier1"
}

###
POST http://192.168.79.130:8080/company/getToken
Content-Type: application/json

{
    "API_KEY": "9947a69346d8018f8a762bb3e15cc5031381d646704f043ddcbff1a48fa4f257",
    "API_SECRET": "U2FsdGVkX19ZmJtWb6vKz+3K4aEqu/kbLwfgKxrITa42lKPxCpuuoN8HQY+o0jK9lP5iXFKFiDaTq+gjnJFRRcZX+ksfB8y9PRQucSgCg7poOhhUOKUc1me2iQZbdzsOPTUIm/lA82AClU1GLq34f5OuiWpGHS5nvqiFEsmbbcDSPCb8YO+C3F8HYzdTrHt5"
}

###
POST http://192.168.79.130:8080/company/verifyToken
Content-Type: application/json


{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBUElfS0VZIjoiOTk0N2E2OTM0NmQ4MDE4ZjhhNzYyYmIzZTE1Y2M1MDMxMzgxZDY0NjcwNGYwNDNkZGNiZmYxYTQ4ZmE0ZjI1NyIsIkFQSV9TRUNSRVQiOiJVMkZzZEdWa1gxOVptSnRXYjZ2S3orM0s0YUVxdS9rYkx3ZmdLeHJJVGE0MmxLUHhDcHV1b044SFFZK28waks5bFA1aVhGS0ZpRGFUcStnam5KRlJSY1pYK2tzZkI4eTlQUlF1Y1NnQ2c3cG9PaGhVT0tVYzFtZTJpUVpiZHpzT1BUVUltL2xBODJBQ2xVMUdMcTM0ZjVPdWlXcEdIUzVudnFpRkVzbWJiY0RTUENiOFlPK0MzRjhIWXpkVHJIdDUiLCJpYXQiOjE1Njk4MTk0MjMsImV4cCI6MTU2OTgxOTYwM30.oOebczjVKyi-5THa5Fo2pjq_lBqHGba6QBwbGjrujbM"
}

###
POST http://192.168.79.130:8080/company/getPersonalInfoByIdentifier
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBUElfS0VZIjoiOTk0N2E2OTM0NmQ4MDE4ZjhhNzYyYmIzZTE1Y2M1MDMxMzgxZDY0NjcwNGYwNDNkZGNiZmYxYTQ4ZmE0ZjI1NyIsIkFQSV9TRUNSRVQiOiJVMkZzZEdWa1gxOVptSnRXYjZ2S3orM0s0YUVxdS9rYkx3ZmdLeHJJVGE0MmxLUHhDcHV1b044SFFZK28waks5bFA1aVhGS0ZpRGFUcStnam5KRlJSY1pYK2tzZkI4eTlQUlF1Y1NnQ2c3cG9PaGhVT0tVYzFtZTJpUVpiZHpzT1BUVUltL2xBODJBQ2xVMUdMcTM0ZjVPdWlXcEdIUzVudnFpRkVzbWJiY0RTUENiOFlPK0MzRjhIWXpkVHJIdDUiLCJpYXQiOjE1Njk4MTc5NDQsImV4cCI6MTU2OTgxODEyNH0.LR9ttf9V-qqBhf28Y3Wt1iTrhsAZsfJjh23VFdyUI-U

{
    "identifier": "identifier1"
}